# Test configuration for multi-turn evaluator

evaluator:
  type: multiturn
  user_simulator_model:
    provider: anthropic
    model_id: claude-3-haiku-20240307
  max_turns: 3
  temperature: 0.7

models:
  - provider: anthropic
    model_id: claude-3-opus-20240229
    max_response_tokens: 1000

runs_per_model: 1

autograders: []

scenarios:
  - ../evals/deceptiveness_24_07_filtered/coding_deceptiveness/*

extra_items: []