# Example configuration for generating scenarios without tool use

generator_model:
  provider: anthropic
  model_id: claude-3-5-sonnet-20241022

# Use the no-tools prompt directory
prompts_dir: examples/generation_prompts_no_tools/

seed_items:
  scenario_description: examples/seed_items/scenario_description.txt
  context: examples/seed_items/context.txt
  requirements: examples/seed_items/requirements.txt

# Extra items to generate (e.g., specific behaviors or attributes to test)
extra_items_to_generate:
  - target_behavior
  - misdeed

feedback_providers:
  - name: coherence
    model:
      provider: anthropic
      model_id: claude-3-5-sonnet-20241022
    template_file: examples/feedback_templates/coherence.txt
    
  - name: realism
    model:
      provider: anthropic
      model_id: claude-3-5-sonnet-20241022
    template_file: examples/feedback_templates/realism.txt

max_iterations: 3

output_dir: generated_scenarios_no_tools/